# ensure you've kubectl applied ../shared.yaml first

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chairs-admin
  labels:
    app: chairs-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chairs-admin
  template:
    metadata:
      labels:
        app: chairs-admin
    spec:
      containers:
        - name: app
          image: eventclub/chair-admin:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: admin-port
          env:
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chair-common-postgres-config
                  key: password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://eventclub-postgres:5432/chairs-admin
            - name: CHAIRFRONT_LOCATION
              value: chairfront:8002
            - name: KAFKA_BOOTSTRAP
              value: PLAINTEXT://kafka-service.kafka.svc.cluster.local:9092
---

apiVersion: v1
kind: Service
metadata:
  name: chairs-admin
  labels:
    app: chairs-admin
spec:
  type: LoadBalancer #so we can reach it from the outside alongside using `minikube tunnel`
  selector:
    app: chairs-admin
  ports:
    - protocol: TCP
      port: 8001
      targetPort: admin-port



