# ensure you've kubectl applied ../shared.yaml first

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chairfront
  labels:
    app: chairfront
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chairfront
  template:
    metadata:
      labels:
        app: chairfront
    spec:
      containers:
        - name: app
          image: eventclub/chairfront:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: chairfront-port
          env:
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chair-common-postgres-config
                  key: password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://eventclub-postgres:5432/chairfront
---

apiVersion: v1
kind: Service
metadata:
  name: chairfront
  labels:
    app: chairfront
spec:
  type: LoadBalancer
  selector:
    app: chairfront
  ports:
    - protocol: TCP
      port: 8002
      targetPort: chairfront-port


